/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
   Suppress this file with MULLE_SOURCETREE_TO_C_IMPORT_FILE NONE|DISABLE.
*/

#ifndef _mulle_serializable_import_h__
#define _mulle_serializable_import_h__

# import <Foundation/Foundation.h>   // Foundation

#endif
